#!/bin/bash

set -e

mkdir -p /mnt/config
LODEV=$(losetup -f)
losetup -P "$LODEV" /dev/mmcblk2boot0
mount -r "$LODEV"p1 /mnt/config/

CONFIG=$(ls /mnt/config/*.json)
cat "$CONFIG"
umount /mnt/config
losetup -d "$LODEV"
