#!/bin/bash

. /etc/rebuild-settings
wifidev=`nmcli dev | grep "wifi " | cut -d' ' -f1`
hotspot_SSID="Recore"
hotspot_PW="12345678"

create_hotspot() {
  echo "Creating hotspot"
  nmcli con add type wifi ifname "$wifidev" con-name Hotspot ssid "$hotspot_SSID"
  nmcli con modify Hotspot 802-11-wireless.mode ap
  nmcli con modify Hotspot 802-11-wireless.band bg
  nmcli con modify Hotspot 802-11-wireless.channel 1
  nmcli con modify Hotspot ipv4.method shared
  nmcli con modify Hotspot ipv4.addresses 192.168.50.1/24
  nmcli con modify Hotspot connection.autoconnect-priority -10
  nmcli con modify Hotspot connection.autoconnect yes
  nmcli con modify Hotspot wifi-sec.key-mgmt wpa-psk
  nmcli con modify Hotspot wifi-sec.psk "$hotspot_PW"
}

create_client() {
  echo "Creating wifi client config"
  nmcli con add type wifi ifname "$wifidev" con-name Client ssid "$WIFI_SSID"
  nmcli con modify Client wifi-sec.key-mgmt wpa-psk
  nmcli con modify Client wifi-sec.psk "$WIFI_PSK"
  nmcli con up Client
}

if [ ! -f /etc/NetworkManager/system-connections/Hotspot.nmconnection ]; then
  create_hotspot
fi

if [ ! -f /etc/NetworkManager/system-connections/Client.nmconnection ]; then
  if [ "${WIFI_SSID}" != "" ]; then
    create_client
  fi
fi
