# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

# default values
setenv load_addr "0x45000000"
setenv overlay_error "false"
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv rootfstype "ext4"
setenv console "both"
setenv docker_optimizations "on"
setenv bootlogo "false"
setenv splashfile "boot.bmp"
setenv splashimage "0x66000000"

setenv vendor "allwinner"

# Remember the default fdtfile provided by u-boot and delete the vendor name
if setexpr subfdt sub ${vendor}/ "" ${fdtfile};then
	setenv deffdt_file ${subfdt}
fi

# Remember the default u-boot fdtdir
setenv deffdt_dir "${prefix}dtb"
if test "$fdtdir" = ""; then setenv fdtdir "${deffdt_dir}/${vendor}";fi

# Print boot source
itest.b *0x10028 == 0x00 && echo "U-boot loaded from SD"
itest.b *0x10028 == 0x02 && echo "U-boot loaded from eMMC or secondary SD"
itest.b *0x10028 == 0x03 && echo "U-boot loaded from SPI"

echo "Boot script loaded from ${devtype}"

if test -e ${devtype} ${devnum} ${prefix}armbianEnv.txt; then
	load ${devtype} ${devnum} ${load_addr} ${prefix}armbianEnv.txt
	env import -t ${load_addr} ${filesize}
fi

# Show a splash image from the boot partition, if one is there.
# ${devtype}/${devnum} rather than a fixed device, so this works whether we
# booted from eMMC or USB. The load is guarded: an image without a splash
# file simply skips it rather than failing the boot.
# Disable by setting splashfile= (empty) in armbianEnv.txt.
if test -n "${splashfile}"; then
	if load ${devtype} ${devnum} ${splashimage} ${prefix}${splashfile}; then
		# Wipe the panel before drawing, or the splash lands on top of the
		# console text rather than replacing it (#84). boot.bmp is 480x480
		# and centred, U-Boot has no scaler, and the panel is far bigger -
		# so `bmp display` only ever covers the middle of a screen that by
		# now holds ~20 lines of output (USB enumeration, the autoboot
		# countdown, the mmc scan), and the rest stays visible around it.
		#
		# Our u-boot no longer puts vidconsole in stdout, so on a current
		# board there is nothing here to clear. Keep it anyway: u-boot
		# lives in eMMC and is not necessarily as new as this script.
		#
		# Point stdout at vidconsole alone for that one command: with
		# CONFIG_VIDEO_ANSI=y cls clears by *printing* an escape sequence,
		# not by touching the video device, so it only works while
		# vidconsole is a console - and leaving serial in would blank the
		# boot log in whatever terminal is watching it.
		setenv stdout vidconsole
		cls
		# Stop U-Boot printing over its own splash. Everything echoed from
		# here on would otherwise be drawn onto the panel - unrotated,
		# since U-Boot knows nothing about the panel orientation. Serial
		# keeps the full log, and the kernel gets its console from
		# ${consoleargs} regardless of this.
		#
		# stderr is left alone on purpose: the panel should stay quiet,
		# not go mute. See the failure branches below.
		setenv stdout serial
		# Nested if so a failure here cannot abort the boot script. An
		# older u-boot on eMMC without CONFIG_CMD_BMP would fail on an
		# unknown command, and that must not stop the board booting.
		if bmp display ${splashimage} m m; then
			echo "Splash displayed"
		else
			# Nothing on the panel left to protect, so give the video
			# console back - a board failing this early is one someone
			# will want to watch without a serial cable.
			setenv stdout serial,vidconsole
			echo "Splash failed to display"
		fi
	fi
fi

# Delete the vendor's name from the fdtfile variable and record the result
# after the file with the environment variables has been read
if setexpr subfdt sub ${vendor}/ "" ${fdtfile};then
	setenv fdtfile ${subfdt}
fi

# In this shell, we can only check the existence of the file.
# Make a check of reasonable ways to find the dtb file.
# Set the true value of the paths.
if test -e ${devtype} ${devnum} "${fdtdir}/${fdtfile}"; then
	echo "Load fdt: ${fdtdir}/${fdtfile}"
else
	echo "The file ${fdtfile} was not found in the path ${fdtdir}"
	if test -e ${devtype} ${devnum} "${deffdt_dir}/${fdtfile}"; then
		setenv fdtdir "${deffdt_dir}"
		echo "Load fdt: ${fdtdir}/${fdtfile}"
	else
		if test -e ${devtype} ${devnum} "${deffdt_dir}/${vendor}/${deffdt_file}"; then
			setenv fdtdir "${deffdt_dir}/${vendor}"
			setenv fdtfile "${deffdt_file}"
			echo "Load fdt: ${fdtdir}/${fdtfile}"
		else
			if test -e ${devtype} ${devnum} "${deffdt_dir}/${deffdt_file}"; then
				setenv fdtdir "${deffdt_dir}"
				setenv fdtfile "${deffdt_file}"
				echo "Load fdt: ${fdtdir}/${fdtfile}"
			fi
		fi
	fi
fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=ttyS0,115200 console=tty1"; fi
if test "${console}" = "serial"; then setenv consoleargs "console=ttyS0,115200"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC it was loaded from
# mmc 0 is always mapped to device u-boot (2016.09+) was loaded from
if test "${devtype}" = "mmc"; then part uuid mmc 1:1 partuuid; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=memory"; fi

if load ${devtype} ${devnum} ${fdt_addr_r} ${fdtdir}/${fdtfile}; then
	echo "Loaded ${fdtdir}/${fdtfile}"
else
	# The search above already gave up out loud, but only on serial. Without
	# a device tree nothing after this works, so say it on the panel too.
	setenv stdout serial,vidconsole
	echo "BOOT FAILED: no device tree at ${fdtdir}/${fdtfile}"
fi
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${fdtdir}/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
if test "${overlay_error}" = "true"; then
	echo "Error applying DT overlays, restoring original DT"
	load ${devtype} ${devnum} ${fdt_addr_r} ${fdtdir}/${fdtfile}
else
	if load ${devtype} ${devnum} ${load_addr} ${fdtdir}/overlay/${overlay_prefix}-fixup.scr; then
		echo "Applying kernel provided DT fixup script (${overlay_prefix}-fixup.scr)"
		source ${load_addr}
	fi
	if test -e ${devtype} ${devnum} ${prefix}fixup.scr; then
		load ${devtype} ${devnum} ${load_addr} ${prefix}fixup.scr
		echo "Applying user provided fixup script (fixup.scr)"
		source ${load_addr}
	fi
fi

# From here the panel is showing the splash and nothing else, which is right
# until something goes wrong - at which point a board that just sits on a nice
# logo forever is worse than one that says why. U-Boot routes almost nothing to
# stderr (see u-boot patch 9), so these are the messages a user actually gets:
# put the video console back and print in plain words what could not be loaded.
if load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}uInitrd; then
	echo "Loaded ${prefix}uInitrd"
else
	setenv stdout serial,vidconsole
	echo "BOOT FAILED: cannot load ${prefix}uInitrd from ${devtype} ${devnum}"
fi
if load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image; then
	echo "Loaded ${prefix}Image"
else
	setenv stdout serial,vidconsole
	echo "BOOT FAILED: cannot load ${prefix}Image from ${devtype} ${devnum}"
fi

booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Only reached if booti did not boot - it does not return on success.
setenv stdout serial,vidconsole
echo "BOOT FAILED: the kernel did not start"

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
