#!/bin/bash

# This script is run only once, the first time Rebuild boots after being flashed

set -e

. /etc/rebuild-settings

log() {
    echo "$1" | tee -a /var/log.hdd/rebuild-first-run.log
}

echo "Starting rebuild first run script"
echo "--Beginning of first run script--" > /var/log.hdd/rebuild-first-run.log

log "Running flash-stm32 script"
/usr/local/bin/flash-stm32

log "Disabling rebuild-first-run.service"
systemctl disable rebuild-first-run.service
