#!/bin/bash

# This script is run only once, the first time Rebuild boots after being flashed

log() {
    echo "$1" | tee -a /var/log.hdd/rebuild-first-run.log
}

echo "Starting rebuild first run script"
echo "--Beginning of first run script--" > /var/log.hdd/rebuild-first-run.log

HARDWARE_REVISION=$(get-recore-revision)
log "Found Recore hardware revision ${HARDWARE_REVISION}"
if [ "${HARDWARE_REVISION}" == "a8" ]; then
    log "Starting and enabling usb-role-switch.timer"
    systemctl enable usb-role-switch.timer
    systemctl start usb-role-switch.timer
fi

log "Disabling rebuild-first-run.service"
systemctl disable rebuild-first-run.service
